[colors.primary]
background = "0x2a2f38"
foreground = "0xe1e3e4"

[colors.normal]
black = "0x181a1c"
red = "0xff6578"
green = "0x9dd274"
yellow = "0xeacb64"
blue = "0x72cce8"
magenta = "0xba9cf3"
cyan = "0xf69c5e"
white = "0xe1e3e4"

[colors.bright]
black = "0x828a9a"
red = "0xff6578"
green = "0x9dd274"
yellow = "0xeacb64"
blue = "0x72cce8"
magenta = "0xba9cf3"
cyan = "0xf69c5e"
white = "0xe1e3e4"

