#set -ga terminal-overrides ",xterm-256color:Tc"
set -q -g status-utf8 on
setw -q -g utf8 on
set history-limit 10000
set -g default-terminal "screen-256color"
set -g base-index 1
set -g pane-base-index 1
set -g mouse on

# catppuccin
# ==========
#  mkdir -p ~/.config/tmux/plugins/catppuccin
#  git clone -b v2.3.0 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux


set -g @catppuccin_flavor 'macchiato'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '
set -g status-right-length 100
