# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O3 -flto=auto -pipe"

# graphite (COMMENT IF NOT BOOTSTRAPPED YET)
COMMON_FLAGS="${COMMON_FLAGS} -floop-block -fgraphite-identity -floop-parallelize-all"

# My ThinkPad P14s Gen 6 with a Core Ultra 7 255H, resolved march=native
COMMON_FLAGS="${COMMON_FLAGS} -march=arrowlake -mabm -mno-kl -mno-pconfig -mno-sgx -mno-widekl -mshstk -mwbnoinvd --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=24576"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

RUSTFLAGS="${RUSTFLAGS} -Ctarget-cpu=native -Copt-level=3"
GRUB_PLATFORMS="efi-64"
ACCEPT_LICENSE="@BINARY-REDISTRIBUTABLE"
MAKEOPTS="-j16 -l16"
#MAKEOPTS="-j12 -l12"
#MAKEOPTS="-j6 -l6"

# systemd use flags
USE="X wayland qt5 qt6 kde sound-server pipewire pulseaudio"
USE="dist-kernel screencast flatpak bluetooth -elogind systemd"
USE="pipewire-alsa gstreamer lto pgo graphite polly jit dlang_single_target_dmd-2_111"
USE="-webengine -gnome -gtk"

FEATURES="candy parallel-fetch parallel-install"
EMERGE_DEFAULT_OPTS="--quiet-build=y --with-bdeps=y"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://mirrors.tuna.tsinghua.edu.cn/gentoo \
    https://mirror.freedif.org/gentoo \
    https://enceladus.sg.ext.planetunix.net/pub/gentoo/ \
    https://mirrors.kernel.org/gentoo/ \
    https://gentoo.osuosl.org/"
