# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[librewolf]
location = /var/db/repos/librewolf
sync-type = git
sync-uri = https://codeberg.org/librewolf/gentoo.git

[gentoo]
location = /var/db/repos/gentoo
sync-type = git
sync-uri = https://github.com/gentoo-mirror/gentoo

[dlang]
location = /var/db/repos/dlang
sync-type = git
sync-uri = https://github.com/gentoo/dlang.git

[crossdev]
location = /var/db/repos/crossdev
